language: php
php:
    - 7.4

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - sudo apt-get update > /dev/null

before_script:
    - composer install

script:
    - php vendor/bin/codecept run unit
