language: php
php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - sudo apt-get update > /dev/null

before_script:
    - composer install
    - cd ./app

script: php ../vendor/bin/codecept run unit
