language: php
php:
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update > /dev/null

before_script:
  - composer install

jobs:
  include:
  - name: AppOne test
    script:
      - cd ./app
      - php ../vendor/bin/codecept run unit
  - name: AppTwo test
    script:
      - cd ./app2
      - php ../vendor/bin/codecept run unit

